#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <time.h>

#define NUM_THREADS 10       // Number of threads
#define POINTS_PER_THREAD 100000000 // Points generated by each thread

int count_in_circle = 0;    // Shared count of points within the circle
pthread_mutex_t mutex;      // Mutex for protecting the shared count

// Function for each thread to generate points and count those within the circle
void* monte_carlo(void* arg) {
    int local_count = 0;    // Local count for points within the circle
    unsigned int seed = time(NULL) ^ pthread_self(); // Seed for random number generation

    for (int i = 0; i < POINTS_PER_THREAD; i++) {
        double x = (double)rand_r(&seed) / RAND_MAX; // Random x between 0 and 1
        double y = (double)rand_r(&seed) / RAND_MAX; // Random y between 0 and 1

        // Check if the point (x, y) is within the unit circle
        if (x * x + y * y <= 1) {
            local_count++;
        }
    }

    // Lock mutex before updating global count
    pthread_mutex_lock(&mutex);
    count_in_circle += local_count;
    pthread_mutex_unlock(&mutex); // Unlock mutex

    pthread_exit(0);
}

int main() {
    pthread_t threads[NUM_THREADS];
    pthread_mutex_init(&mutex, NULL); // Initialize mutex

    // Create threads
    for (int i = 0; i < NUM_THREADS; i++) {
        pthread_create(&threads[i], NULL, monte_carlo, NULL);
    }

    // Wait for all threads to finish
    for (int i = 0; i < NUM_THREADS; i++) {
        pthread_join(threads[i], NULL);
    }

    // Calculate the approximate value of π
    int total_points = NUM_THREADS * POINTS_PER_THREAD;
    double pi_estimate = (double)count_in_circle / total_points * 4;

    // Print result
    printf("Estimated value of Pi = %f\n", pi_estimate);

    // Clean up
    pthread_mutex_destroy(&mutex);

    return 0;
}

