/* a) */
SELECT E.LNAME, E.FNAME
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.SSN = W.ESSN
JOIN PROJECT P ON P.PNUMBER = W.PNO
WHERE E.DNO=5 
AND P.PNAME = 'ProductX'
AND W.HOURS > 10

/* b) */
SELECT E.LNAME, E.FNAME
FROM EMPLOYEE E
JOIN DEPENDENT D ON E.SSN = D.ESSN
WHERE E.FNAME = D.DEPENDENT_NAME

/* c) */
SELECT E1.LNAME, E1.FNAME 
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.SUPERSSN = E2.SSN
WHERE E2.FNAME = 'Franklin' AND E2.LNAME = 'Wong'

/* d) */
SELECT LNAME, FNAME
FROM EMPLOYEE  
WHERE SSN NOT IN
(SELECT E.SSN
FROM WORKS_ON W, EMPLOYEE E
WHERE E.SSN = W.ESSN
)
/* e) */
SELECT E.LNAME, E.FNAME, E.ADDRESS
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.SSN = W.ESS
JOIN PROJECT P ON W.PNO = P.PNUMBER
WHERE P.PLOCATION = 'Houston'
AND E.DNO NOT IN(
SELECT D.DNUMBER
FROM DEPARTMENT D
JOIN DEPT_LOCATIONS L ON D.DNUMBER = L.DNUMBER
WHERE L.DLOCATION = 'Houston'
)

// f) 
SELECT E.LNAME, E.FNAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.SSN = D.MGRSSN
WHERE E.SSN = D.MGRSSN AND E.SSN NOT IN
(
SELECT E.SSN
FROM EMPLOYEE E
JOIN DEPENDENT DE ON E.SSN = DE.ESSN
WHERE E.SSN = DE.ESSN
)

